{% set name = "esptool" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ea9bcd7eb263d380a4fe0170856a10e4c65e3f38c757ebdc73584c8dd8322da

build:
  skip: true  # [py<310]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - esptool = esptool.__init__:_main
    - espsecure = espsecure.__init__:_main
    - espefuse = espefuse.__init__:_main
    - esp_rfc2217_server = esp_rfc2217_server.__init__:main
    - esptool.py = esptool.__init__:_main                       # [win]
    - espsecure.py = espsecure.__init__:_main                   # [win]
    - espefuse.py = espefuse.__init__:_main                     # [win]
    - esp_rfc2217_server.py = esp_rfc2217_server.__init__:main  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools >=64
  run:
    - bitstring >=3.1.6,!=4.2.0
    - click <9
    - cryptography >=43.0.0
    - intelhex
    - python
    - pyserial >=3.3
    - pyyaml >=5.1
    - reedsolo >=1.5.3,<1.8
    - rich-click

test:
  imports:
    - esptool
  commands:
    - esptool -h
    - espsecure -h
    - espefuse -h
    - esptool.py -h
    - espsecure.py -h
    - espefuse.py -h
    - esp_rfc2217_server.py -h

about:
  home: https://github.com/espressif/esptool
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A serial utility to communicate & flash code to Espressif ESP8266 & ESP32 chips.
  doc_url: https://github.com/espressif/esptool/wiki
  dev_url: https://github.com/espressif/esptool

extra:
  recipe-maintainers:
    - m-rossi
